#### NumPy Unary Operations
Eg: sum,prod,max,min,mean,std,var

In [1]:
import numpy as np

In [2]:
# On 1D array 
data = np.array([21, 10, 14, 23, 56])

In [3]:
data.sum() 

124

In [4]:
data.prod()

3786720

In [5]:
# On 2D array
data = np.arange(24).reshape(6, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
data.sum(axis=0) # col

array([60, 66, 72, 78])

In [7]:
data.sum(axis=1) # rows 

array([ 6, 22, 38, 54, 70, 86])

In [8]:
data.sum() # default = total sum of all elements

276

In [9]:
data.prod(axis=1)

array([     0,    840,   7920,  32760,  93024, 212520])

In [10]:
data.prod(axis=0)

array([      0,  208845,  665280, 1514205])

#### Data Types in NumPy

In [11]:
## Check the datatype - dtype
data.dtype

dtype('int32')

In [12]:
# At the time of creation

a = [-1,2,3,4,5,6]
a = np.array(a,dtype=bool)
a.reshape((3,2))

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [13]:
## Change the datatype - astype()
# i - integer
# b - boolean
# f - float
# S - string

a = np.arange(1,12,2).reshape((2,3))
a.astype(dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

#### Splitting and Joining in NumPy Array

##### Spliting a 1D array
###### syntax - numpy.split(array, int/list)

In [14]:
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# Split into 3 equal parts
np.split(data, 4)

# Split at specific indices with a different example

np.split(data, [1, 3, 6, 9, 11])

# # [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]

# 0-1 -> [0]
# 1-3 -> [1,2]
# 3-6 -> [3,4,5]
# 6-9 -> [6,7,8]
# 9-11 -> [9,10]
# 11 -> [11]


[array([0]),
 array([1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10]),
 array([11])]

In [16]:
data = np.arange(12)
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [17]:
np.split(data,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [18]:
#     0  1   2   3   4   5   6   7   8  9   10 11
#[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22]

# np.split(data, [1, 3, 6, 9, 11])

# 0-1 -> [0]
# 1-3 -> [2,4]
# 3-6 -> [6,8,10]
# 6-9 -> [12,14,16]
# 9-11 -> [18,20]
# 11 -> [22]

##### Spliting a 2D array
###### syntax - numpy.split(array, int/list,axis)
- axis - 1 ---> column wise
- axis - 0 ---> row wise

In [20]:
data_2d = np.arange(24).reshape(6, 4)
data_2d

# Split into 3 equal parts- default row wise
np.split(data_2d, 3)


# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15],
#        [16, 17, 18, 19],
#        [20, 21, 22, 23]])

# Split at specific indices with a different example
np.split(data_2d, [1, 3, 6, 9, 11])

# 0-1 - > [0,1,2,3]
# 1-3 -> [4,5,6,7]
#        [8,9,10,11]
# 3-6 -> [12, 13, 14, 15],
#        [16, 17, 18, 19],
#        [20, 21, 22, 23]
        
# 6-9 -> []
# 9-11 -> []

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [21]:
# Split at specific indices along rows
np.split(data_2d, [2, 4, 6, 9], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [ ]:
data_2d