#### Splitting across columns

In [1]:
import numpy as np

In [2]:
# syntax - np.split(data_variable_name,int/list,axis=0/1) 0 -> rows 1-> col
data_2d = np.arange(24).reshape(6, 4)
data_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
# Split into 3 equal parts along columns
np.split(data_2d, 2, axis=1)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [24]:
data_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# data_2d rows - axis 0 

# [1,3]
np.split(data_2d, [1,3], axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [5]:
# Split at specific indices along columns
np.split(data_2d, [1, 3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

#### NumPy Concatenation
#### Syntax : numpy.concatenate((arr1, arr2, …), axis=0)
- axis - 1 ---> column wise
- axis - 0 ---> row wise


In [6]:
a = np.array([["Apples", "Banana"], ["Apricot", "Blackberry"]])
b = np.array([["Guava", "Blueberry"], ["Cherry", "Grapes"]])
a


array([['Apples', 'Banana'],
       ['Apricot', 'Blackberry']], dtype='<U10')

In [7]:
b

array([['Guava', 'Blueberry'],
       ['Cherry', 'Grapes']], dtype='<U9')

In [8]:
# Concatenate along rows
np.concatenate((a, b), axis=0)

array([['Apples', 'Banana'],
       ['Apricot', 'Blackberry'],
       ['Guava', 'Blueberry'],
       ['Cherry', 'Grapes']], dtype='<U10')

In [9]:
# When concatenating along columns, ensure the number of rows is equal
a = np.array([["Apples", "Banana","Lychee"], ["Apricot", "Blackberry","Kiwi"]])
b = np.array([["Guava", "Blueberry"], ["Cherry", "Grapes"]])


In [17]:
# When concatenating along rows, ensure the number of columns is equal
a = np.array([["Apples", "Banana"], 
              ["Apricot", "Blackberry"],
              ['Papaya','Pineapple'],
              ['Banana','Strawberry']])
b = np.array([["Guava", "Blueberry"], 
              ["Cherry", "Grapes"]])

# Concatenate along rows
np.concatenate((a, b), axis=0)

array([['Apples', 'Banana'],
       ['Apricot', 'Blackberry'],
       ['Papaya', 'Pineapple'],
       ['Banana', 'Strawberry'],
       ['Guava', 'Blueberry'],
       ['Cherry', 'Grapes']], dtype='<U10')

In [16]:
# When concatenating along columns, ensure the number of rows is equal
a = np.array([["Apples", "Banana","Lychee"], 
              ["Apricot", "Blackberry","Kiwi"],])
b = np.array([["Guava", "Blueberry"], 
              ["Cherry", "Grapes"]])
np.concatenate((a,b),axis=1)

array([['Apples', 'Banana', 'Lychee', 'Guava', 'Blueberry'],
       ['Apricot', 'Blackberry', 'Kiwi', 'Cherry', 'Grapes']],
      dtype='<U10')

In [ ]:
b

In [19]:
# Concatenate along rows
np.concatenate((a, b), axis=0)

array([['Apples', 'Banana'],
       ['Apricot', 'Blackberry'],
       ['Papaya', 'Pineapple'],
       ['Banana', 'Strawberry'],
       ['Guava', 'Blueberry'],
       ['Cherry', 'Grapes']], dtype='<U10')

### Pandas


- data representation is better as compared to numpy
- Pandas is a Python library used for working with data sets.
- analyzing, cleaning, exploring, and manipulating data.
- heterogenous data

- can load any kind of data - excel , csv , tsv, sql , clipboard
- get stats
- manupulate the data

In [ ]:
### Installation of pandas
pip install pandas

#### Import Pandas

In [ ]:
import pandas as pd

### pandas has 2 data structure

1. Series - 1D
2. Dataframe - 2D

In [ ]:
# Syntax -> pd.Series(list/numpy array/,index=)

In [ ]:
# 1. Using list
data = pd.Series([12,22,32,44],index=['a','b','c','d'])
data

In [ ]:
a = np.arange(5)
pd.Series(a,index=['hasna','prajwal','suresh','ramesh','prarthana'])

In [ ]:
example = {'a':1,'b':2,'c':3}
pd.Series(example)

In [ ]:
example = {'a':1,'b':2,'c':3}
pd.Series(example)

In [ ]:
# 1. Using list
data = pd.Series([12,22,32,44],index=['a','b','c','d'])
data

In [ ]:
# Custom Indexing
data['c']

In [ ]:
# Zero Indexing 

data[2]

In [ ]:
data = pd.Series([12,22,32,44],index=['a','b','c','d'])
data

In [ ]:
# Slicing using Custom Indexing
# Inclusive of stop

data['b':'d']

In [ ]:
# Slicing Using Zero indexing

data[1:3]