## Numpy

- NumPy is a Python library used for working with arrays.
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- The array object in NumPy is called ndarray, 
- it provides a lot of supporting functions that make working with ndarray very easy
- Easy to perform Matrix multiplication


### Installation of NumPy
pip install numpy

### Import NumPy

In [2]:
import numpy as np

- NumPy is used to work with arrays. 
- The array object in NumPy is called ndarray.
- We can create a NumPy ndarray object by using the array() function.

### How to create a numpy

In [5]:
# Create a 0-D array with value 42
arr = np.array(42)
arr

array(42)

In [4]:
# Create a 1-D array containing the values 1,2,3,4,5:
list1 = [1,2,3,4,5]
ex = np.array(list1)
ex

array([1, 2, 3, 4, 5])

In [6]:
# An array that has 1-D arrays as its elements is called a 2-D array.
list2 = [[1,2],[2,3]]
ndarray = np.array(list2)
ndarray

array([[1, 2],
       [2, 3]])

In [7]:
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [10]:
### The numpy.arange() function is used to generate an array with evenly spaced values within a specified interval. 
### The function returns a one-dimensional array of type numpy.ndarray.
### 3. arange(start,stop,step) - always return 1 dimension
a = np.arange(1,10,2)
a


array([1, 3, 5, 7, 9])

##### Attributes

In [11]:
# size - returns int - total number of elements
a.size

5

In [12]:
# ndim - returns the int - returns the dimension of the array 
a.ndim

1

In [13]:
# shape - return a tuple - returns the shape - eg: 2x2
a.shape

(5,)

In [14]:
# dtype - returns the datatype of the array
a.dtype

dtype('int32')

#### Reshaping
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [28]:
### 4. ones(shape) - returns an ndarray with all elements as ones

a = np.ones((2,3,4))
a*5

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [29]:
### 5. zeros(shape) - return an ndarray within all elements as zeros

b = np.zeros((4,4))
b+6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [25]:
### 6. full(shape) - return an ndarray within all elements as mentioned
np.full((4,5),fill_value = 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [43]:
# infer
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.

a = np.arange(24)
a.reshape(2,4,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [44]:
# flatten()
# Flattening array means converting a multidimensional array into a 1D array.
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
a.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
### Operations using array
# Addition, Subtraction, Multiplication: Element-wise operations.

a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
b = np.arange(1,11).reshape(2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
# Addition 
a+b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [55]:
# Subtracton
a-b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [56]:
a*b

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [57]:
# dot product / matrix multiplication 

# a = 2x3 n*p
# b = 3x4 p*m
# result = 2x4 n*m

In [58]:
a = [[1,1],[2,2],[3,3]]
b = [[2,4],[2,6]]

In [60]:
a = np.array(a)
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [61]:
b = np.array(b)
b

array([[2, 4],
       [2, 6]])

In [62]:
a.dot(b)

array([[ 4, 10],
       [ 8, 20],
       [12, 30]])

In [66]:
a = np.arange(1,10)
b = np.arange(1,10)

In [67]:
a/b

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Access Array Elements  ( Indexing )
 - Array indexing is the same as accessing an array element.

 - You can access an array element by referring to its index number.

 - The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [8]:
# Index on 1D array
arr = np.array([1, 2, 3, 4])
arr[2]

3

###### Access 2-D Arrays
 - To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
 - Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
# 1. variable_name[row][col]
# 2. variable_name[row,col]
a[1,2]

7

##### Slicing

- We can also define the step, like this: [start:end:step].
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1


##### variable_name[row(start:stop:step),col(start:stop:step)]


In [4]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
## 0 1
## 6 7
# variable_name[row(start:stop:step),col(start:stop:step)]
# a[0:2:,0:2:]
# a[2::,4::]
# a[2:4:1,4:6:1]

array([[16, 17],
       [22, 23]])

In [83]:
# 9 10
# 21 22
# variable_name[row(start:stop:step),col(start:stop:step)]
a[1:6:2,3:5]


array([[ 9, 10],
       [21, 22]])

In [84]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [85]:
## 1 3
## 7 9
a[0:2,1:4:2]

array([[1, 3],
       [7, 9]])

In [86]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [89]:
# variable_name[row(start:stop:step),col(start:stop:step)]
## 0 2 4 
## 6 8 10
a[0:2,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [90]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [91]:
# variable_name[row(start:stop:step),col(start:stop:step)]
## 6   8  10
## 18 20  22

a[1:4:2,0:5:2]

array([[ 6,  8, 10],
       [18, 20, 22]])